---
- name: Tear down existing service {{ db_service }}
  community.docker.docker_compose:
    project_src: "{{ app_src }}"
    state: absent

- name: Create and start service {{ db_service }}
  community.docker.docker_compose:
    project_src: "{{ app_src }}"
    state: present
    services:
      - "{{ db_service }}"
  register: output

- debug:
    var: output
