services:
  db:
    restart: unless-stopped
    image: mongo:5.0
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017

  api:
    restart: unless-stopped
    build:
      context: ./api
    # depends_on:
    #   - db
    environment:
      - MONGO_URI=mongodb://172.17.0.1:27017/vdt
  
  api-lb:
    restart: unless-stopped
    image: nginx:1.22.0-alpine
    volumes:
      - ./api/nginx/lb/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    ports:
      - 5000:80

  web:
    restart: unless-stopped
    build:
      context: ./web
      args:
        - VITE_APP_BASE_URL=http://localhost:5000
    # depends_on:
    #   - api
    environment:
      - VITE_APP_BASE_URL=http://172.17.0.1:5000

  web-lb:
    restart: unless-stopped
    image: nginx:1.22.0-alpine
    volumes:
      - ./web/nginx/lb/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    ports:
      - 80:80
