services:
  db:
    restart: unless-stopped
    image: mongo:5.0
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017

  api:
    restart: unless-stopped
    image: duclm278/api:${APP_VERSION:-latest}
    environment:
      - MONGO_URI=mongodb://172.17.0.1:27017/vdt
  
  api-lb:
    restart: unless-stopped
    image: nginx:1.22.0-alpine
    volumes:
      - ./api-lb/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    ports:
      - 5000:80

  web:
    restart: unless-stopped
    image: duclm278/web:${APP_VERSION:-latest}

  web-lb:
    restart: unless-stopped
    image: nginx:1.22.0-alpine
    volumes:
      - ./web-lb/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    ports:
      - 80:80
