---
- name: Create and start service {{ web_service }}
  community.docker.docker_compose:
    project_src: "{{ app_src }}"
    state: present
    services:
      - "{{ web_service }}"

- name: Scale service {{ web_service }}
  community.docker.docker_compose:
    project_src: "{{ app_src }}"
    scale: "{ '{{ web_service }}': '{{ web_scale }}' }"
