---
local:
  hosts:
    localhost:
      ansible_user: duc
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python3
      ansible_become_user: root
      ansible_become_password: "{{ become_password }}"

db:
  hosts:
    vm01:
      ansible_user: duc
      ansible_host: 192.168.0.105
      ansible_python_interpreter: /usr/bin/python3
      ansible_become_user: root
      ansible_become_password: "{{ become_password }}"
  children:
    local:

api:
  hosts:
    vm01:
      ansible_user: duc
      ansible_host: 192.168.0.105
      ansible_python_interpreter: /usr/bin/python3
      ansible_become_user: root
      ansible_become_password: "{{ become_password }}"
  children:
    local:

web:
  hosts:
    vm01:
      ansible_user: duc
      ansible_host: 192.168.0.105
      ansible_python_interpreter: /usr/bin/python3
      ansible_become_user: root
      ansible_become_password: "{{ become_password }}"
  children:
    local:

all:
  children:
    db:
    api:
    web:
