---
- name: Set up Docker
  hosts: all
  become: true
  gather_facts: true
  roles:
    - common
  tags: [docker]

- name: Tear down existing services
  hosts: "{{ cleanup_hosts | default('all') }}"
  become: false
  gather_facts: true
  roles:
    - cleanup
  tags: [cleanup]

- name: Deploy db
  hosts: db
  become: false
  gather_facts: false
  roles:
    - db
  tags: [deploy, db]

- name: Deploy api
  hosts: api
  become: false
  gather_facts: false
  roles:
    - api
    - { role: lb, lb_service: "{{ api_lb_service }}" }
  tags: [deploy, api]

- name: Deploy web
  hosts: web
  become: false
  gather_facts: false
  roles:
    - web
    - { role: lb, lb_service: "{{ web_lb_service }}" }
  tags: [deploy, web]
