---
- name: Create and start service {{ api_service }}
  community.docker.docker_compose:
    project_src: "{{ app_src }}"
    state: present
    services:
      - "{{ api_service }}"

- name: Scale service {{ api_service }}
  community.docker.docker_compose:
    project_src: "{{ app_src }}"
    scale: "{ '{{ api_service }}': '{{ api_scale }}' }"
