# Source: https://github.com/docker/build-push-action

name: release

on:
  push:
    tags:
      - "**"

env:
  API_DIR: ./app/api
  API_IMAGE: api
  WEB_DIR: ./app/web
  WEB_IMAGE: web

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image for api
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.API_DIR }}
          file: ${{ env.API_DIR }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.API_IMAGE }}:${{ github.ref_name }}
      - name: Build and push image for web
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.WEB_DIR }}
          file: ${{ env.WEB_DIR }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.WEB_IMAGE }}:${{ github.ref_name }}
          build-args: |
            VITE_APP_BASE_URL=http://localhost:5000
